name: Reproduce Detach Crash
# 3535 safe_read magic unstable during detach from threaded app
on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake gcc g++
    - name: Download DynamoRIO
      run: |
        # wget https://github.com/DynamoRIO/dynamorio/releases/download/release_6_0_0/DynamoRIO-Linux-6.0.0-6.tar.gz
        # tar -xzf DynamoRIO-Linux-6.0.0-6.tar.gz
        wget https://github.com/DynamoRIO/dynamorio/releases/download/cronbuild-10.91.19860/DynamoRIO-Linux-10.91.19860.tar.gz
        tar -xzf DynamoRIO-Linux-10.91.19860.tar.gz
    - name: Build Multithreaded Application
      run: |
        gcc -o myapp myapp.c -lpthread

    - name: Run Application with DynamoRIO
      run: |
        ./DynamoRIO-Linux-10.91.19860/bin64/drrun -- ./myapp
    - name: Build sample
      run: | 
        cd DynamoRIO-Linux-10.91.19860/samples
        mkdir build
        cd build
        cmake ..
        make
        cd bin
        ls -l
    - name: Simulate Detach
      run: |
        for i in {1..100}; do
          echo "Run $i"
          ./DynamoRIO-Linux-10.91.19860/bin64/drrun -c DynamoRIO-Linux-10.91.19860/samples/bin64/libmemtrace_simple.so -- ./myapp
        done
